# Generated by Django 2.2.1 on 2019-05-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_access', '0004_auto_20190531_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='login',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='login',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
