# Generated by Django 2.2.1 on 2019-06-11 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_access', '0012_auto_20190607_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluation',
            options={'ordering': ['session__date'], 'verbose_name': 'evaluation'},
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='skill',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='levels',
            field=models.CharField(default='', max_length=100, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills_evaluated', to='teacher_access.Skill'),
        ),
    ]
