# Generated by Django 2.2.1 on 2019-06-11 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_access', '0013_auto_20190611_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='skills',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='general',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SkillEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
                ('level', models.IntegerField(default=0)),
                ('eval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_access.Evaluation')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_access.Skill')),
            ],
            options={
                'verbose_name': 'skill evaluation',
                'ordering': ['skill'],
            },
        ),
    ]
