# Generated by Django 2.2.1 on 2019-06-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_access', '0014_auto_20190611_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='aimed_at',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='beyond',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='insufficient',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='weak',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
