# Generated by Django 2.2.1 on 2019-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_access', '0016_remove_skill_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='general',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='skillevaluation',
            name='comment',
            field=models.CharField(max_length=300),
        ),
    ]
