# Generated by Django 2.2.1 on 2019-06-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_access', '0017_auto_20190613_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='general',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
